package gmsm_oracle_test

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tjfoc/gmsm/sm4"
)

// ---- Vector records (all binary fields stored as hex strings) ----

type Sm3Vector struct {
	Name   string `json:"name"`
	Msg    string `json:"msg"`    // hex
	Digest string `json:"digest"` // hex
}
type Sm4BlockVector struct {
	Name   string `json:"name"`
	Key    string `json:"key"`
	Block  string `json:"block"`
	Cipher string `json:"cipher"`
}
type Sm4EcbVector struct {
	Name   string `json:"name"`
	Key    string `json:"key"`
	Plain  string `json:"plain"`
	Cipher string `json:"cipher"`
}
type Sm4CbcVector struct {
	Name   string `json:"name"`
	Key    string `json:"key"`
	IV     string `json:"iv"`
	Plain  string `json:"plain"`
	Cipher string `json:"cipher"`
}
type Sm2EncVector struct {
	Name   string `json:"name"`
	PubX   string `json:"pub_x"`
	PubY   string `json:"pub_y"`
	PrivD  string `json:"priv_d"`
	Msg    string `json:"msg"`
	Cipher string `json:"cipher"` // ASN.1 (C1C3C2) ciphertext
}
type Sm2SigVector struct {
	Name string `json:"name"`
	PubX string `json:"pub_x"`
	PubY string `json:"pub_y"`
	UID  string `json:"uid"`
	Msg  string `json:"msg"`
	R    string `json:"r"`
	S    string `json:"s"`
	Der  string `json:"der"` // ASN.1 DER signature
}
type Vectors struct {
	Sm3    []Sm3Vector    `json:"sm3"`
	Sm4Blk []Sm4BlockVector `json:"sm4_block"`
	Sm4Ecb []Sm4EcbVector  `json:"sm4_ecb"`
	Sm4Cbc []Sm4CbcVector  `json:"sm4_cbc"`
	Sm2Enc []Sm2EncVector  `json:"sm2_encrypt"`
	Sm2Sig []Sm2SigVector  `json:"sm2_sign"`
}

// V accumulates the oracle vectors; populated by the gen* functions and written
// to disk by TestMain after all tests have run.
var V Vectors

// root returns the workspace root (parent of this go/ directory).
func root() string {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return filepath.Dir(wd)
}

func hexb(b []byte) string { return hex.EncodeToString(b) }

// ---- raw (unpadded) SM4 helpers, so MoonBit's non-padding ECB/CBC match ----

func rawSm4Ecb(key, plain []byte) []byte {
	c, err := sm4.NewCipher(key)
	if err != nil {
		panic(err)
	}
	out := make([]byte, len(plain))
	for i := 0; i < len(plain); i += 16 {
		c.Encrypt(out[i:i+16], plain[i:i+16])
	}
	return out
}

func rawSm4Cbc(key, iv, plain []byte) []byte {
	c, err := sm4.NewCipher(key)
	if err != nil {
		panic(err)
	}
	out := make([]byte, len(plain))
	prev := make([]byte, 16)
	copy(prev, iv)
	for i := 0; i < len(plain); i += 16 {
		blk := make([]byte, 16)
		for j := 0; j < 16; j++ {
			blk[j] = plain[i+j] ^ prev[j]
		}
		c.Encrypt(blk, blk)
		copy(out[i:], blk)
		copy(prev, blk)
	}
	return out
}

// ---- TestMain: generate vectors, run tests, then emit docs + MoonBit tests ----

func TestMain(m *testing.M) {
	// gmsm's randFieldElement ignores the reader passed to GenerateKey/Sm2Sign/
	// EncryptAsn1 and always reads from the global crypto/rand.Reader. Override it
	// with a deterministic reader so the oracle produces STABLE vectors and does
	// not block on the (unavailable) OS randomness source.
	rand.Reader = newDetReader()

	genSm3()
	genSm4()
	genSm2()
	code := m.Run()
	if code == 0 {
		if err := writeDocs(); err != nil {
			fmt.Fprintln(os.Stderr, "writeDocs:", err)
			code = 1
		}
		if err := writeMoonbit(); err != nil {
			fmt.Fprintln(os.Stderr, "writeMoonbit:", err)
			code = 1
		}
	}
	os.Exit(code)
}

// ---- Documentation (human readable + machine readable) ----

func writeDocs() error {
	r := root()
	if err := os.MkdirAll(filepath.Join(r, "docs"), 0o755); err != nil {
		return err
	}

	j, err := json.MarshalIndent(V, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(r, "docs", "sm_vectors.json"), j, 0o644); err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("# SM Algorithm Test Vectors\n\n")
	b.WriteString("Auto-generated by the Go `gmsm` oracle in `go/` (`go test`).\n\n")
	b.WriteString("These vectors are the **reference inputs and outputs** for the MoonBit\n")
	b.WriteString("cross-language tests:\n")
	b.WriteString("- `sm3/go_vectors_test.mbt`\n")
	b.WriteString("- `sm4/go_vectors_test.mbt`\n")
	b.WriteString("- `sm2/go_vectors_test.mbt`\n\n")
	b.WriteString("The MoonBit tests load these values (via generated `_test.mbt` files) and\n")
	b.WriteString("assert that MoonBit's SM2/SM3/SM4 implementations reproduce the Go outputs.\n\n")

	b.WriteString("## SM3 (hash)\n\n")
	b.WriteString("| name | msg (hex) | digest (hex) |\n|---|---|---|\n")
	for _, v := range V.Sm3 {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", v.Name, v.Msg, v.Digest)
	}
	b.WriteString("\n")

	b.WriteString("## SM4 (block cipher)\n\n")
	b.WriteString("### single block\n\n")
	b.WriteString("| name | key (hex) | block (hex) | cipher (hex) |\n|---|---|---|---|\n")
	for _, v := range V.Sm4Blk {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", v.Name, v.Key, v.Block, v.Cipher)
	}
	b.WriteString("\n### ECB (raw, no padding)\n\n")
	b.WriteString("| name | key (hex) | plain (hex) | cipher (hex) |\n|---|---|---|---|\n")
	for _, v := range V.Sm4Ecb {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", v.Name, v.Key, v.Plain, v.Cipher)
	}
	b.WriteString("\n### CBC (raw, no padding)\n\n")
	b.WriteString("| name | key (hex) | iv (hex) | plain (hex) | cipher (hex) |\n|---|---|---|---|---|\n")
	for _, v := range V.Sm4Cbc {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", v.Name, v.Key, v.IV, v.Plain, v.Cipher)
	}
	b.WriteString("\n")

	b.WriteString("## SM2 (public key cryptography)\n\n")
	b.WriteString("### encryption (ASN.1 C1C3C2 ciphertext; MoonBit decrypts it)\n\n")
	b.WriteString("| name | pub_x (hex) | pub_y (hex) | priv_d (hex) | msg (hex) | cipher (hex) |\n|---|---|---|---|---|---|\n")
	for _, v := range V.Sm2Enc {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n", v.Name, v.PubX, v.PubY, v.PrivD, v.Msg, v.Cipher)
	}
	b.WriteString("\n### signature (DER; MoonBit verifies it)\n\n")
	b.WriteString("| name | pub_x (hex) | pub_y (hex) | uid (hex) | msg (hex) | r (hex) | s (hex) | der (hex) |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|\n")
	for _, v := range V.Sm2Sig {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s | %s |\n", v.Name, v.PubX, v.PubY, v.UID, v.Msg, v.R, v.S, v.Der)
	}
	b.WriteString("\n")

	return os.WriteFile(filepath.Join(r, "docs", "sm_vectors.md"), []byte(b.String()), 0o644)
}

// ---- MoonBit test file generation ----

const mbHelpers = `///|
/// Auto-generated by the Go gmsm oracle (go/). DO NOT EDIT BY HAND.
/// The vectors are loaded from docs/sm_vectors.json (and documented in
/// docs/sm_vectors.md). Each test asserts that MoonBit's SM implementation
/// reproduces the Go reference output.

///|
fn go_hex_nibble(c : UInt16) -> Int {
  if c >= 48 && c <= 57 {
    (c - 48).to_int()
  } else if c >= 65 && c <= 70 {
    (c - 65).to_int() + 10
  } else if c >= 97 && c <= 102 {
    (c - 97).to_int() + 10
  } else {
    abort("go: invalid hex char")
  }
}

///|
fn go_hex_to_bytes(s : String) -> Bytes {
  let n = s.length() / 2
  Bytes::makei(n, fn(i) {
    let hi = go_hex_nibble(s[i * 2])
    let lo = go_hex_nibble(s[i * 2 + 1])
    ((hi << 4) | lo).to_byte()
  })
}

///|
fn go_nibble_to_char(n : Int) -> Char {
  if n < 10 {
    Int::unsafe_to_char(n + '0'.to_int())
  } else {
    Int::unsafe_to_char(n - 10 + 'a'.to_int())
  }
}

///|
fn go_byte_to_hex(b : Byte) -> String {
  let hi = (b.to_int() >> 4) & 0xF
  let lo = b.to_int() & 0xF
  let buf = StringBuilder::new()
  buf.write_char(go_nibble_to_char(hi))
  buf.write_char(go_nibble_to_char(lo))
  buf.to_string()
}

///|
fn go_bytes_to_hex(b : Bytes) -> String {
  let buf = StringBuilder::new()
  for i = 0; i < b.length(); i = i + 1 {
    buf.write_string(go_byte_to_hex(b[i]))
  }
  buf.to_string()
}
`

func writeMoonbit() error {
	r := root()

	// SM3
	{
		var b strings.Builder
		b.WriteString(mbHelpers)
		for _, v := range V.Sm3 {
			fmt.Fprintf(&b, "\n///|\ntest %q {\n  let h = @sm3.sm3_sum(go_hex_to_bytes(%q))\n  assert_eq(go_bytes_to_hex(h), %q)\n}\n",
				"go_sm3_"+v.Name, v.Msg, v.Digest)
		}
		if err := os.WriteFile(filepath.Join(r, "sm3", "go_vectors_test.mbt"), []byte(b.String()), 0o644); err != nil {
			return err
		}
	}

	// SM4
	{
		var b strings.Builder
		b.WriteString(mbHelpers)
		for _, v := range V.Sm4Blk {
			fmt.Fprintf(&b, "\n///|\ntest %q {\n  let key = go_hex_to_bytes(%q)\n  let block = go_hex_to_bytes(%q)\n  let cipher = @sm4.sm4_encrypt_block(key, block)\n  assert_eq(go_bytes_to_hex(cipher), %q)\n}\n",
				"go_sm4_block_"+v.Name, v.Key, v.Block, v.Cipher)
		}
		for _, v := range V.Sm4Ecb {
			fmt.Fprintf(&b, "\n///|\ntest %q {\n  let key = go_hex_to_bytes(%q)\n  let plain = go_hex_to_bytes(%q)\n  let cipher = @sm4.sm4_encrypt_ecb(key, plain)\n  assert_eq(go_bytes_to_hex(cipher), %q)\n}\n",
				"go_sm4_ecb_"+v.Name, v.Key, v.Plain, v.Cipher)
		}
		for _, v := range V.Sm4Cbc {
			fmt.Fprintf(&b, "\n///|\ntest %q {\n  let key = go_hex_to_bytes(%q)\n  let iv = go_hex_to_bytes(%q)\n  let plain = go_hex_to_bytes(%q)\n  let cipher = @sm4.sm4_encrypt_cbc(key, iv, plain)\n  assert_eq(go_bytes_to_hex(cipher), %q)\n}\n",
				"go_sm4_cbc_"+v.Name, v.Key, v.IV, v.Plain, v.Cipher)
		}
		if err := os.WriteFile(filepath.Join(r, "sm4", "go_vectors_test.mbt"), []byte(b.String()), 0o644); err != nil {
			return err
		}
	}

	// SM2
	{
		var b strings.Builder
		b.WriteString(mbHelpers)
		b.WriteString(`
///|
fn go_load_priv(d : Bytes) -> @sm2.SM2PrivateKey {
  try {
    @sm2.private_key_from_bytes(@sm2.sm2_p256(), d)
  } catch {
    _ => abort("go: bad private key")
  }
}

///|
fn go_load_pub(x : Bytes, y : Bytes) -> @sm2.SM2PublicKey {
  try {
    @sm2.public_key_from_xy(@sm2.sm2_p256(), x, y)
  } catch {
    _ => abort("go: bad public key")
  }
}
`)
		for _, v := range V.Sm2Enc {
			name := "go_sm2_dec_" + v.Name
			fmt.Fprintf(&b, "\n///|\ntest %q {\n  let privkey = go_load_priv(go_hex_to_bytes(%q))\n  let cipher = go_hex_to_bytes(%q)\n  let plain = try {\n    @sm2.sm2_decrypt_asn1(privkey, cipher)\n  } catch {\n    _ => abort(%q)\n  }\n  assert_eq(go_bytes_to_hex(plain), %q)\n}\n",
				name, v.PrivD, v.Cipher, name+": decrypt failed", v.Msg)
		}
		for _, v := range V.Sm2Sig {
			name := "go_sm2_verify_" + v.Name
			fmt.Fprintf(&b, "\n///|\ntest %q {\n  let pubkey = go_load_pub(go_hex_to_bytes(%q), go_hex_to_bytes(%q))\n  let msg = go_hex_to_bytes(%q)\n  let uid = go_hex_to_bytes(%q)\n  let der = go_hex_to_bytes(%q)\n  assert_true(@sm2.sm2_verify_der(pubkey, msg, uid, der))\n}\n",
				name, v.PubX, v.PubY, v.Msg, v.UID, v.Der)
		}
		if err := os.WriteFile(filepath.Join(r, "sm2", "go_vectors_test.mbt"), []byte(b.String()), 0o644); err != nil {
			return err
		}
	}

	return nil
}
